"""Generated declarative CLI metadata for the Typer frontend.

This module contains only literals so root help and shell completion do not
import the ONNX-backed command implementation modules.
"""

# This generated literal catalogue intentionally keeps long help strings intact.
# ruff: noqa: E501

from __future__ import annotations

from typing import Any

COMMAND_SPECS: list[dict[str, Any]] = \
[{'module': 'ttsforge.cli.commands_conversion',
  'function': 'convert',
  'name': 'convert',
  'parent': None,
  'help': 'Convert an EPUB file to an audiobook.\n'
          '\n'
          'EPUB_FILE is the path to the EPUB file to convert.',
  'parameters': [{'name': 'ctx', 'kind': 'context'},
                 {'name': 'epub_file',
                  'kind': 'argument',
                  'decls': ['epub_file'],
                  'annotation': 'Path',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': None},
                 {'name': 'output',
                  'kind': 'option',
                  'decls': ['-o', '--output'],
                  'annotation': 'Path | None',
                  'python_type': 'Path',
                  'path': {'exists': False,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Output file path. Defaults to input filename with new extension.'},
                 {'name': 'output_format',
                  'kind': 'option',
                  'decls': ['-f', '--format', 'output_format'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['wav', 'mp3', 'flac', 'opus', 'm4b'],
                  'help': 'Output audio format.'},
                 {'name': 'voice',
                  'kind': 'option',
                  'decls': ['-v', '--voice'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['af',
                              'af_alloy',
                              'af_aoede',
                              'af_bella',
                              'af_heart',
                              'af_jessica',
                              'af_kore',
                              'af_nicole',
                              'af_nova',
                              'af_river',
                              'af_sarah',
                              'af_sky',
                              'am_adam',
                              'am_echo',
                              'am_eric',
                              'am_fenrir',
                              'am_liam',
                              'am_michael',
                              'am_onyx',
                              'am_puck',
                              'am_santa',
                              'bf_alice',
                              'bf_emma',
                              'bf_isabella',
                              'bf_lily',
                              'bm_daniel',
                              'bm_fable',
                              'bm_george',
                              'bm_lewis',
                              'ef_dora',
                              'em_alex',
                              'em_santa',
                              'ff_siwis',
                              'hf_alpha',
                              'hf_beta',
                              'hm_omega',
                              'hm_psi',
                              'if_sara',
                              'im_nicola',
                              'jf_alpha',
                              'jf_gongitsune',
                              'jf_nezumi',
                              'jf_tebukuro',
                              'jm_kumo',
                              'pf_dora',
                              'pm_alex',
                              'pm_santa',
                              'zf_xiaobei',
                              'zf_xiaoni',
                              'zf_xiaoxiao',
                              'zm_yunjian',
                              'zm_yunxi',
                              'zm_yunxia',
                              'zm_yunyang'],
                  'help': 'Voice to use for TTS.'},
                 {'name': 'language',
                  'kind': 'option',
                  'decls': ['-l', '--language'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['a', 'b', 'd', 'e', 'f', 'h', 'i', 'j', 'p', 'z'],
                  'help': 'Language code (a=American English, b=British English, etc.).'},
                 {'name': 'lang',
                  'kind': 'option',
                  'decls': ['--lang'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Override language for phonemization (e.g., 'de', 'fr', 'en-us'). By "
                          'default, language is determined from the voice.',
                  'default': None},
                 {'name': 'speed',
                  'kind': 'option',
                  'decls': ['-s', '--speed'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.5,
                  'max': 2.0,
                  'help': 'Speech speed (0.5 to 2.0).'},
                 {'name': 'use_gpu',
                  'kind': 'option',
                  'decls': ['--gpu/--no-gpu', 'use_gpu'],
                  'annotation': 'bool | None',
                  'help': 'Enable/disable GPU acceleration.',
                  'default': None},
                 {'name': 'chapters',
                  'kind': 'option',
                  'decls': ['--chapters'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Chapters to convert (e.g., '1-5', '1,3,5', 'all')."},
                 {'name': 'skip_chapters',
                  'kind': 'option',
                  'decls': ['--skip-chapters'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Chapters to skip (e.g., '5', '2,4,6', '10-12')."},
                 {'name': 'silence',
                  'kind': 'option',
                  'decls': ['--silence'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Silence duration between chapters in seconds.'},
                 {'name': 'pause_clause',
                  'kind': 'option',
                  'decls': ['--pause-clause'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Pause after clauses in seconds (default: 0.25).',
                  'default': None},
                 {'name': 'pause_sentence',
                  'kind': 'option',
                  'decls': ['--pause-sentence'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Pause after sentences in seconds (default: 0.2).',
                  'default': None},
                 {'name': 'pause_paragraph',
                  'kind': 'option',
                  'decls': ['--pause-paragraph'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Pause after paragraphs in seconds (default: 0.75).',
                  'default': None},
                 {'name': 'pause_variance',
                  'kind': 'option',
                  'decls': ['--pause-variance'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Random variance added to pauses in seconds (default: 0.05).',
                  'default': None},
                 {'name': 'random_seed',
                  'kind': 'option',
                  'decls': ['--seed', 'random_seed'],
                  'annotation': 'int | None',
                  'python_type': 'int',
                  'help': 'Random seed for reproducible pause variance and randomized handling.',
                  'default': None},
                 {'name': 'pause_mode',
                  'kind': 'option',
                  'decls': ['--pause-mode'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Pause mode: 'tts', 'manual', or 'auto' (default: auto).",
                  'default': None},
                 {'name': 'enable_short_sentence',
                  'kind': 'option',
                  'decls': ['--disable-short-sentence', 'enable_short_sentence'],
                  'annotation': 'bool | None',
                  'help': 'Disable special handling for short sentences.',
                  'default': None,
                  'flag_value': False},
                 {'name': 'short_sentence',
                  'kind': 'option',
                  'decls': ['--short-sentence'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': 'Short-sentence handling config, e.g. '
                          "'mode=randomized,threshold=30,selection=auto,max-tries=5' or "
                          "'config=path/to/short_sentence.json'.",
                  'default': None},
                 {'name': 'announce_chapters',
                  'kind': 'option',
                  'decls': ['--announce-chapters/--no-announce-chapters', 'announce_chapters'],
                  'annotation': 'bool | None',
                  'help': 'Read chapter titles aloud before chapter content (default: enabled).',
                  'default': None},
                 {'name': 'chapter_pause',
                  'kind': 'option',
                  'decls': ['--chapter-pause'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Pause duration after chapter title announcement in seconds (default: '
                          '2.0).',
                  'default': None},
                 {'name': 'title',
                  'kind': 'option',
                  'decls': ['--title'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': 'Title metadata for the audiobook.'},
                 {'name': 'author',
                  'kind': 'option',
                  'decls': ['--author'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': 'Author metadata for the audiobook.'},
                 {'name': 'cover',
                  'kind': 'option',
                  'decls': ['--cover'],
                  'annotation': 'Path | None',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Cover image for m4b format.'},
                 {'name': 'yes',
                  'kind': 'option',
                  'decls': ['-y', '--yes'],
                  'annotation': 'bool',
                  'help': 'Skip confirmation prompts.',
                  'is_flag': True},
                 {'name': 'verbose',
                  'kind': 'option',
                  'decls': ['--verbose'],
                  'annotation': 'bool',
                  'help': 'Show detailed output.',
                  'is_flag': True},
                 {'name': 'split_mode',
                  'kind': 'option',
                  'decls': ['--split-mode', 'split_mode'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['auto', 'line', 'paragraph', 'sentence', 'clause'],
                  'help': 'Text splitting mode: auto, line, paragraph, sentence, clause.',
                  'default': None},
                 {'name': 'resume',
                  'kind': 'option',
                  'decls': ['--resume/--no-resume', 'resume'],
                  'annotation': 'bool',
                  'help': 'Enable/disable resume capability (default: enabled).',
                  'default': True},
                 {'name': 'generate_ssmd_only',
                  'kind': 'option',
                  'decls': ['--generate-ssmd', 'generate_ssmd_only'],
                  'annotation': 'bool',
                  'help': 'Generate only SSMD files without creating audio (for manual editing).',
                  'is_flag': True},
                 {'name': 'detect_emphasis',
                  'kind': 'option',
                  'decls': ['--detect-emphasis/--no-detect-emphasis', 'detect_emphasis'],
                  'annotation': 'bool',
                  'help': 'Detect emphasis (italic/bold) from HTML tags in EPUB files (default: '
                          'disabled).',
                  'default': False},
                 {'name': 'fresh',
                  'kind': 'option',
                  'decls': ['--fresh'],
                  'annotation': 'bool',
                  'help': 'Discard any previous progress and start conversion from scratch.',
                  'is_flag': True},
                 {'name': 'keep_chapter_files',
                  'kind': 'option',
                  'decls': ['--keep-chapters', 'keep_chapter_files'],
                  'annotation': 'bool',
                  'help': 'Keep individual chapter audio files after conversion.',
                  'is_flag': True},
                 {'name': 'voice_blend',
                  'kind': 'option',
                  'decls': ['--voice-blend', 'voice_blend'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Blend multiple voices (e.g., 'af_nicole:50,am_michael:50')."},
                 {'name': 'voice_database',
                  'kind': 'option',
                  'decls': ['--voice-db', 'voice_database'],
                  'annotation': 'Path | None',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Path to custom voice database (SQLite).'},
                 {'name': 'use_mixed_language',
                  'kind': 'option',
                  'decls': ['--use-mixed-language/--no-use-mixed-language', 'use_mixed_language'],
                  'annotation': 'bool | None',
                  'help': 'Enable mixed-language support (auto-detect multiple languages in text).',
                  'default': None},
                 {'name': 'mixed_language_primary',
                  'kind': 'option',
                  'decls': ['--mixed-language-primary', 'mixed_language_primary'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Primary language for mixed-language mode (e.g., 'de', 'en-us')."},
                 {'name': 'mixed_language_allowed',
                  'kind': 'option',
                  'decls': ['--mixed-language-allowed', 'mixed_language_allowed'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Comma-separated list of allowed languages (e.g., 'de,en-us')."},
                 {'name': 'mixed_language_confidence',
                  'kind': 'option',
                  'decls': ['--mixed-language-confidence', 'mixed_language_confidence'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'max': 1.0,
                  'help': 'Detection confidence threshold for mixed-language mode (0.0-1.0, '
                          'default: 0.7).'},
                 {'name': 'phoneme_dictionary_path',
                  'kind': 'option',
                  'decls': ['--phoneme-dict', 'phoneme_dictionary_path'],
                  'annotation': 'str | None',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Path to custom phoneme dictionary JSON file for pronunciation '
                          'overrides.'},
                 {'name': 'phoneme_dict_case_sensitive',
                  'kind': 'option',
                  'decls': ['--phoneme-dict-case-sensitive/--no-phoneme-dict-case-sensitive',
                            'phoneme_dict_case_sensitive'],
                  'annotation': 'bool | None',
                  'help': 'Make phoneme dictionary matching case-sensitive (default: '
                          'case-insensitive).',
                  'default': None},
                 {'name': 'subchapter_markers',
                  'kind': 'option',
                  'decls': ['--subchapter-marker', 'subchapter_markers'],
                  'annotation': 'tuple[str, ...]',
                  'help': 'Exact line marker to convert into a paragraph pause. Repeat for '
                          'multiple markers.',
                  'multiple': True}]},
 {'module': 'ttsforge.cli.commands_conversion',
  'function': 'list_chapters',
  'name': 'list',
  'parent': None,
  'help': 'List chapters in a file.\n\nEPUB_FILE is the path to the file (EPUB, TXT, or SSMD).',
  'parameters': [{'name': 'epub_file',
                  'kind': 'argument',
                  'decls': ['epub_file'],
                  'annotation': 'Path',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': None}]},
 {'module': 'ttsforge.cli.commands_conversion',
  'function': 'info',
  'name': 'info',
  'parent': None,
  'help': 'Show metadata and information about a file.\n'
          '\n'
          'EPUB_FILE is the path to the file (EPUB, TXT, or SSMD).',
  'parameters': [{'name': 'epub_file',
                  'kind': 'argument',
                  'decls': ['epub_file'],
                  'annotation': 'Path',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': None}]},
 {'module': 'ttsforge.cli.commands_conversion',
  'function': 'sample',
  'name': 'sample',
  'parent': None,
  'help': 'Generate a sample audio file to test TTS settings.\n'
          '\n'
          'If no TEXT is provided, uses a default sample text.\n'
          '\n'
          'Examples:\n'
          '\n'
          '    ttsforge sample\n'
          '\n'
          '    ttsforge sample "Hello, this is a test."\n'
          '\n'
          '    ttsforge sample --voice am_adam --speed 1.2 -o test.wav\n'
          '\n'
          '    ttsforge sample --play  # Play directly without saving\n'
          '\n'
          '    ttsforge sample --play -o test.wav  # Play and save to file',
  'parameters': [{'name': 'ctx', 'kind': 'context'},
                 {'name': 'text',
                  'kind': 'argument',
                  'decls': ['text'],
                  'annotation': 'str | None',
                  'help': None,
                  'required': False,
                  'default': None},
                 {'name': 'output',
                  'kind': 'option',
                  'decls': ['-o', '--output'],
                  'annotation': 'Path | None',
                  'python_type': 'Path',
                  'path': {'exists': False,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Output file path (default: ./sample.wav).'},
                 {'name': 'output_format',
                  'kind': 'option',
                  'decls': ['-f', '--format', 'output_format'],
                  'annotation': 'str',
                  'python_type': 'str',
                  'choices': ['wav', 'mp3', 'flac', 'opus', 'm4b'],
                  'help': 'Output audio format.',
                  'default': 'wav'},
                 {'name': 'voice',
                  'kind': 'option',
                  'decls': ['-v', '--voice'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "TTS voice to use or voice blend (e.g., 'af_sky' or "
                          "'af_nicole:50,am_michael:50')."},
                 {'name': 'language',
                  'kind': 'option',
                  'decls': ['-l', '--language'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['a', 'b', 'd', 'e', 'f', 'h', 'i', 'j', 'p', 'z'],
                  'help': 'Language for TTS.'},
                 {'name': 'lang',
                  'kind': 'option',
                  'decls': ['--lang'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Override language for phonemization (e.g., 'de', 'fr', 'en-us').",
                  'default': None},
                 {'name': 'speed',
                  'kind': 'option',
                  'decls': ['-s', '--speed'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.5,
                  'max': 2.0,
                  'help': 'Speech speed (default: 1.0).'},
                 {'name': 'random_seed',
                  'kind': 'option',
                  'decls': ['--seed', 'random_seed'],
                  'annotation': 'int | None',
                  'python_type': 'int',
                  'help': 'Random seed for reproducible pause variance and randomized handling.',
                  'default': None},
                 {'name': 'use_gpu',
                  'kind': 'option',
                  'decls': ['--gpu/--no-gpu', 'use_gpu'],
                  'annotation': 'bool | None',
                  'help': 'Use GPU acceleration if available.',
                  'default': None},
                 {'name': 'split_mode',
                  'kind': 'option',
                  'decls': ['--split-mode', 'split_mode'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['auto', 'line', 'paragraph', 'sentence', 'clause'],
                  'help': 'Text splitting mode for processing.'},
                 {'name': 'play_audio',
                  'kind': 'option',
                  'decls': ['-p', '--play', 'play_audio'],
                  'annotation': 'bool',
                  'help': 'Play audio directly (also saves to file if -o specified).',
                  'is_flag': True},
                 {'name': 'verbose',
                  'kind': 'option',
                  'decls': ['--verbose'],
                  'annotation': 'bool',
                  'help': 'Show detailed output.',
                  'is_flag': True},
                 {'name': 'use_mixed_language',
                  'kind': 'option',
                  'decls': ['--use-mixed-language', 'use_mixed_language'],
                  'annotation': 'bool',
                  'help': 'Enable mixed-language support (auto-detect multiple languages in text).',
                  'is_flag': True},
                 {'name': 'mixed_language_primary',
                  'kind': 'option',
                  'decls': ['--mixed-language-primary', 'mixed_language_primary'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Primary language for mixed-language mode (e.g., 'de', 'en-us')."},
                 {'name': 'mixed_language_allowed',
                  'kind': 'option',
                  'decls': ['--mixed-language-allowed', 'mixed_language_allowed'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Comma-separated list of allowed languages (e.g., 'de,en-us')."},
                 {'name': 'mixed_language_confidence',
                  'kind': 'option',
                  'decls': ['--mixed-language-confidence', 'mixed_language_confidence'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'max': 1.0,
                  'help': 'Detection confidence threshold for mixed-language mode (0.0-1.0, '
                          'default: 0.7).'},
                 {'name': 'phoneme_dictionary_path',
                  'kind': 'option',
                  'decls': ['--phoneme-dict', 'phoneme_dictionary_path'],
                  'annotation': 'str | None',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Path to custom phoneme dictionary JSON file for pronunciation '
                          'overrides.'},
                 {'name': 'phoneme_dict_case_sensitive',
                  'kind': 'option',
                  'decls': ['--phoneme-dict-case-sensitive', 'phoneme_dict_case_sensitive'],
                  'annotation': 'bool',
                  'help': 'Make phoneme dictionary matching case-sensitive (default: '
                          'case-insensitive).',
                  'is_flag': True}]},
 {'module': 'ttsforge.cli.commands_conversion',
  'function': 'read',
  'name': 'read',
  'parent': None,
  'help': 'Read an EPUB or text file aloud with streaming playback.\n'
          '\n'
          'Streams audio in real-time without creating output files.\n'
          'Supports chapter/page selection, position saving, and resume.\n'
          '\n'
          '\x08\n'
          'Examples:\n'
          '    ttsforge read book.epub\n'
          '    ttsforge read book.epub --chapters "1-5"\n'
          '    ttsforge read book.epub --mode pages --pages "1-50"\n'
          '    ttsforge read book.epub --mode pages --start-page 10\n'
          '    ttsforge read book.epub --start-chapter 3\n'
          '    ttsforge read book.epub --resume\n'
          '    ttsforge read book.epub --split sentence\n'
          '    ttsforge read book.epub --list\n'
          '    ttsforge read story.txt\n'
          '    cat story.txt | ttsforge read -\n'
          '\n'
          '\x08\n'
          'Controls:\n'
          '    Ctrl+C - Stop reading (position is saved for resume)',
  'parameters': [{'name': 'ctx', 'kind': 'context'},
                 {'name': 'input_file',
                  'kind': 'argument',
                  'decls': ['input_file'],
                  'annotation': 'Path | None',
                  'python_type': 'Path',
                  'path': {'exists': False,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': None,
                  'required': False,
                  'default': None},
                 {'name': 'voice',
                  'kind': 'option',
                  'decls': ['-v', '--voice'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['af',
                              'af_alloy',
                              'af_aoede',
                              'af_bella',
                              'af_heart',
                              'af_jessica',
                              'af_kore',
                              'af_nicole',
                              'af_nova',
                              'af_river',
                              'af_sarah',
                              'af_sky',
                              'am_adam',
                              'am_echo',
                              'am_eric',
                              'am_fenrir',
                              'am_liam',
                              'am_michael',
                              'am_onyx',
                              'am_puck',
                              'am_santa',
                              'bf_alice',
                              'bf_emma',
                              'bf_isabella',
                              'bf_lily',
                              'bm_daniel',
                              'bm_fable',
                              'bm_george',
                              'bm_lewis',
                              'ef_dora',
                              'em_alex',
                              'em_santa',
                              'ff_siwis',
                              'hf_alpha',
                              'hf_beta',
                              'hm_omega',
                              'hm_psi',
                              'if_sara',
                              'im_nicola',
                              'jf_alpha',
                              'jf_gongitsune',
                              'jf_nezumi',
                              'jf_tebukuro',
                              'jm_kumo',
                              'pf_dora',
                              'pm_alex',
                              'pm_santa',
                              'zf_xiaobei',
                              'zf_xiaoni',
                              'zf_xiaoxiao',
                              'zm_yunjian',
                              'zm_yunxi',
                              'zm_yunxia',
                              'zm_yunyang'],
                  'help': 'TTS voice to use.'},
                 {'name': 'language',
                  'kind': 'option',
                  'decls': ['-l', '--language'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['a', 'b', 'd', 'e', 'f', 'h', 'i', 'j', 'p', 'z'],
                  'help': 'Language for TTS.'},
                 {'name': 'speed',
                  'kind': 'option',
                  'decls': ['-s', '--speed'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'help': 'Speech speed (default: 1.0).'},
                 {'name': 'use_gpu',
                  'kind': 'option',
                  'decls': ['--gpu/--no-gpu', 'use_gpu'],
                  'annotation': 'bool | None',
                  'help': 'Use GPU acceleration if available.',
                  'default': None},
                 {'name': 'content_mode',
                  'kind': 'option',
                  'decls': ['--mode', 'content_mode'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['chapters', 'pages'],
                  'help': 'Split content by chapters or pages (default: chapters).',
                  'default': None},
                 {'name': 'chapters',
                  'kind': 'option',
                  'decls': ['-c', '--chapters'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Chapter selection (e.g., '1-5', '1,3,5', '3-'). Use with --mode "
                          'chapters.'},
                 {'name': 'pages',
                  'kind': 'option',
                  'decls': ['-p', '--pages'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Page selection (e.g., '1-50', '10,20,30'). Use with --mode pages."},
                 {'name': 'start_chapter',
                  'kind': 'option',
                  'decls': ['--start-chapter'],
                  'annotation': 'int | None',
                  'python_type': 'int',
                  'help': 'Start from specific chapter number (1-indexed).'},
                 {'name': 'start_page',
                  'kind': 'option',
                  'decls': ['--start-page'],
                  'annotation': 'int | None',
                  'python_type': 'int',
                  'help': 'Start from specific page number (1-indexed).'},
                 {'name': 'page_size',
                  'kind': 'option',
                  'decls': ['--page-size'],
                  'annotation': 'int | None',
                  'python_type': 'int',
                  'min': 1,
                  'help': 'Synthetic page size in characters (default: 2000). Only for --mode '
                          'pages.',
                  'default': None},
                 {'name': 'resume',
                  'kind': 'option',
                  'decls': ['--resume'],
                  'annotation': 'bool',
                  'help': 'Resume from last saved position.',
                  'is_flag': True},
                 {'name': 'list_content',
                  'kind': 'option',
                  'decls': ['--list', 'list_content'],
                  'annotation': 'bool',
                  'help': 'List chapters/pages and exit without reading.',
                  'is_flag': True},
                 {'name': 'split_mode',
                  'kind': 'option',
                  'decls': ['--split', 'split_mode'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['sentence', 'paragraph'],
                  'help': 'Text splitting mode: sentence (shorter) or paragraph (grouped).',
                  'default': None},
                 {'name': 'pause_clause',
                  'kind': 'option',
                  'decls': ['--pause-clause'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Pause after clauses in seconds.',
                  'default': None},
                 {'name': 'pause_sentence',
                  'kind': 'option',
                  'decls': ['--pause-sentence'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Pause after sentences in seconds.',
                  'default': None},
                 {'name': 'pause_paragraph',
                  'kind': 'option',
                  'decls': ['--pause-paragraph'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Pause after paragraphs in seconds.',
                  'default': None},
                 {'name': 'pause_variance',
                  'kind': 'option',
                  'decls': ['--pause-variance'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Random variance added to pauses in seconds.',
                  'default': None},
                 {'name': 'random_seed',
                  'kind': 'option',
                  'decls': ['--seed', 'random_seed'],
                  'annotation': 'int | None',
                  'python_type': 'int',
                  'help': 'Random seed for reproducible pause variance and randomized handling.',
                  'default': None},
                 {'name': 'pause_mode',
                  'kind': 'option',
                  'decls': ['--pause-mode'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': 'Trim leading/trailing silence from audio.',
                  'default': None},
                 {'name': 'enable_short_sentence',
                  'kind': 'option',
                  'decls': ['--disable-short-sentence', 'enable_short_sentence'],
                  'annotation': 'bool | None',
                  'help': 'Disable special handling for short sentences.',
                  'default': None,
                  'flag_value': False},
                 {'name': 'short_sentence',
                  'kind': 'option',
                  'decls': ['--short-sentence'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': 'Short-sentence handling config, e.g. '
                          "'mode=randomized,threshold=30,selection=auto,max-tries=5' or "
                          "'config=path/to/short_sentence.json'.",
                  'default': None}]},
 {'module': 'ttsforge.cli.commands_phonemes',
  'function': 'phonemes_export',
  'name': 'export',
  'parent': 'phonemes',
  'help': 'Export an EPUB as pre-tokenized phoneme data.\n'
          '\n'
          "This creates a JSON file containing the book's text converted to\n"
          'phonemes and tokens, which can be later converted to audio without\n'
          're-running the phonemization step.\n'
          '\n'
          'Split modes:\n'
          '- paragraph: Split only on double newlines (fewer, longer segments)\n'
          '- sentence: Split on sentence boundaries using spaCy (recommended)\n'
          '- clause: Split on sentences + commas (more, shorter segments)\n'
          '\n'
          'Examples:\n'
          '\n'
          '    ttsforge phonemes export book.epub\n'
          '\n'
          '    ttsforge phonemes export book.epub --readable -o book.readable.txt\n'
          '\n'
          '    ttsforge phonemes export book.epub --language b --chapters 1-5\n'
          '\n'
          '    ttsforge phonemes export book.epub --split-mode clause',
  'parameters': [{'name': 'epub_file',
                  'kind': 'argument',
                  'decls': ['epub_file'],
                  'annotation': 'Path',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': None},
                 {'name': 'output',
                  'kind': 'option',
                  'decls': ['-o', '--output'],
                  'annotation': 'Path | None',
                  'python_type': 'Path',
                  'path': {'exists': False,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Output file path. Defaults to input filename with .phonemes.json '
                          'extension.'},
                 {'name': 'readable',
                  'kind': 'option',
                  'decls': ['--readable'],
                  'annotation': 'bool',
                  'help': 'Export as human-readable text format instead of JSON.',
                  'is_flag': True},
                 {'name': 'language',
                  'kind': 'option',
                  'decls': ['-l', '--language'],
                  'annotation': 'str',
                  'python_type': 'str',
                  'choices': ['a', 'b', 'd', 'e', 'f', 'h', 'i', 'j', 'p', 'z'],
                  'help': 'Language code for phonemization.',
                  'default': 'a'},
                 {'name': 'chapters',
                  'kind': 'option',
                  'decls': ['--chapters'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Chapters to export (e.g., '1-5', '1,3,5', 'all')."},
                 {'name': 'vocab_version',
                  'kind': 'option',
                  'decls': ['--vocab-version'],
                  'annotation': 'str',
                  'python_type': 'str',
                  'help': 'Vocabulary version to use for tokenization.',
                  'default': 'v1.0'},
                 {'name': 'split_mode',
                  'kind': 'option',
                  'decls': ['--split-mode', 'split_mode'],
                  'annotation': 'str',
                  'python_type': 'str',
                  'choices': ['paragraph', 'sentence', 'clause'],
                  'help': 'Split mode: paragraph (newlines), sentence (spaCy), clause (+ commas).',
                  'default': 'sentence'},
                 {'name': 'max_chars',
                  'kind': 'option',
                  'decls': ['--max-chars'],
                  'annotation': 'int',
                  'python_type': 'int',
                  'help': 'Maximum characters per segment (for additional splitting of long '
                          'segments).',
                  'default': 300},
                 {'name': 'subchapter_markers',
                  'kind': 'option',
                  'decls': ['--subchapter-marker', 'subchapter_markers'],
                  'annotation': 'tuple[str, ...]',
                  'help': 'Exact line marker to convert into a paragraph pause. Repeat for '
                          'multiple markers.',
                  'multiple': True}]},
 {'module': 'ttsforge.cli.commands_phonemes',
  'function': 'phonemes_convert',
  'name': 'convert',
  'parent': 'phonemes',
  'help': 'Convert a pre-tokenized phoneme file to audio.\n'
          '\n'
          "PHONEME_FILE should be a JSON file created by 'ttsforge phonemes export'.\n"
          '\n'
          'By default, conversion is resumable (chapter-at-a-time mode). If interrupted,\n'
          're-running the same command will resume from the last completed chapter.\n'
          '\n'
          'Use --streaming for faster conversion without resume capability.\n'
          '\n'
          'Examples:\n'
          '\n'
          '    ttsforge phonemes convert book.phonemes.json\n'
          '\n'
          '    ttsforge phonemes convert book.phonemes.json -v am_adam -o book.m4b\n'
          '\n'
          '    ttsforge phonemes convert book.phonemes.json --chapters 1-5\n'
          '\n'
          '    ttsforge phonemes convert book.phonemes.json --streaming',
  'parameters': [{'name': 'ctx', 'kind': 'context'},
                 {'name': 'phoneme_file',
                  'kind': 'argument',
                  'decls': ['phoneme_file'],
                  'annotation': 'Path',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': None},
                 {'name': 'output',
                  'kind': 'option',
                  'decls': ['-o', '--output'],
                  'annotation': 'Path | None',
                  'python_type': 'Path',
                  'path': {'exists': False,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Output file path. Defaults to input filename with audio extension.'},
                 {'name': 'output_format',
                  'kind': 'option',
                  'decls': ['-f', '--format', 'output_format'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['wav', 'mp3', 'flac', 'opus', 'm4b'],
                  'help': 'Output audio format.'},
                 {'name': 'voice',
                  'kind': 'option',
                  'decls': ['-v', '--voice'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['af',
                              'af_alloy',
                              'af_aoede',
                              'af_bella',
                              'af_heart',
                              'af_jessica',
                              'af_kore',
                              'af_nicole',
                              'af_nova',
                              'af_river',
                              'af_sarah',
                              'af_sky',
                              'am_adam',
                              'am_echo',
                              'am_eric',
                              'am_fenrir',
                              'am_liam',
                              'am_michael',
                              'am_onyx',
                              'am_puck',
                              'am_santa',
                              'bf_alice',
                              'bf_emma',
                              'bf_isabella',
                              'bf_lily',
                              'bm_daniel',
                              'bm_fable',
                              'bm_george',
                              'bm_lewis',
                              'ef_dora',
                              'em_alex',
                              'em_santa',
                              'ff_siwis',
                              'hf_alpha',
                              'hf_beta',
                              'hm_omega',
                              'hm_psi',
                              'if_sara',
                              'im_nicola',
                              'jf_alpha',
                              'jf_gongitsune',
                              'jf_nezumi',
                              'jf_tebukuro',
                              'jm_kumo',
                              'pf_dora',
                              'pm_alex',
                              'pm_santa',
                              'zf_xiaobei',
                              'zf_xiaoni',
                              'zf_xiaoxiao',
                              'zm_yunjian',
                              'zm_yunxi',
                              'zm_yunxia',
                              'zm_yunyang'],
                  'help': 'Voice to use for TTS.'},
                 {'name': 'speed',
                  'kind': 'option',
                  'decls': ['-s', '--speed'],
                  'annotation': 'float',
                  'python_type': 'float',
                  'min': 0.5,
                  'max': 2.0,
                  'help': 'Speech speed.',
                  'default': 1.0},
                 {'name': 'use_gpu',
                  'kind': 'option',
                  'decls': ['--gpu/--no-gpu', 'use_gpu'],
                  'annotation': 'bool | None',
                  'help': 'Enable/disable GPU acceleration.',
                  'default': None},
                 {'name': 'silence',
                  'kind': 'option',
                  'decls': ['--silence'],
                  'annotation': 'float',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Silence between chapters in seconds.',
                  'default': 2.0},
                 {'name': 'pause_clause',
                  'kind': 'option',
                  'decls': ['--pause-clause'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Pause after clauses in seconds (default: 0.25).',
                  'default': None},
                 {'name': 'pause_sentence',
                  'kind': 'option',
                  'decls': ['--pause-sentence'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Pause after sentences in seconds (default: 0.2).',
                  'default': None},
                 {'name': 'pause_paragraph',
                  'kind': 'option',
                  'decls': ['--pause-paragraph'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Pause after paragraphs in seconds (default: 0.75).',
                  'default': None},
                 {'name': 'pause_variance',
                  'kind': 'option',
                  'decls': ['--pause-variance'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Random variance added to pauses in seconds (default: 0.05).',
                  'default': None},
                 {'name': 'random_seed',
                  'kind': 'option',
                  'decls': ['--seed', 'random_seed'],
                  'annotation': 'int | None',
                  'python_type': 'int',
                  'help': 'Random seed for reproducible pause variance and randomized handling.',
                  'default': None},
                 {'name': 'pause_mode',
                  'kind': 'option',
                  'decls': ['--pause-mode'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': 'auto, manual or tts (default: auto).',
                  'default': None},
                 {'name': 'short_sentence',
                  'kind': 'option',
                  'decls': ['--short-sentence'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': 'Short-sentence handling config, e.g. '
                          "'mode=randomized,threshold=30,selection=auto,max-tries=5' or "
                          "'config=path/to/short_sentence.json'.",
                  'default': None},
                 {'name': 'announce_chapters',
                  'kind': 'option',
                  'decls': ['--announce-chapters/--no-announce-chapters', 'announce_chapters'],
                  'annotation': 'bool | None',
                  'help': 'Read chapter titles aloud before chapter content (default: enabled).',
                  'default': None},
                 {'name': 'chapter_pause',
                  'kind': 'option',
                  'decls': ['--chapter-pause'],
                  'annotation': 'float | None',
                  'python_type': 'float',
                  'min': 0.0,
                  'help': 'Pause duration after chapter title announcement in seconds (default: '
                          '2.0).',
                  'default': None},
                 {'name': 'chapters',
                  'kind': 'option',
                  'decls': ['--chapters'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Select chapters to convert (1-based). E.g., '1-5', '3,5,7', or '1-3,7'.",
                  'default': None},
                 {'name': 'title',
                  'kind': 'option',
                  'decls': ['--title'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': 'Audiobook title (for m4b metadata).',
                  'default': None},
                 {'name': 'author',
                  'kind': 'option',
                  'decls': ['--author'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': 'Audiobook author (for m4b metadata).',
                  'default': None},
                 {'name': 'cover',
                  'kind': 'option',
                  'decls': ['--cover'],
                  'annotation': 'Path | None',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Cover image path (for m4b format).',
                  'default': None},
                 {'name': 'voice_blend',
                  'kind': 'option',
                  'decls': ['--voice-blend'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Blend multiple voices. E.g., 'af_nicole:50,am_michael:50'.",
                  'default': None},
                 {'name': 'voice_database',
                  'kind': 'option',
                  'decls': ['--voice-database'],
                  'annotation': 'Path | None',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Path to custom voice database (SQLite).',
                  'default': None},
                 {'name': 'streaming',
                  'kind': 'option',
                  'decls': ['--streaming/--no-streaming', 'streaming'],
                  'annotation': 'bool',
                  'help': 'Use streaming mode (faster, no resume). Default: resumable.',
                  'default': False},
                 {'name': 'keep_chapters',
                  'kind': 'option',
                  'decls': ['--keep-chapters'],
                  'annotation': 'bool',
                  'help': 'Keep intermediate chapter files after merging.',
                  'is_flag': True},
                 {'name': 'yes',
                  'kind': 'option',
                  'decls': ['-y', '--yes'],
                  'annotation': 'bool',
                  'help': 'Skip confirmation prompts.',
                  'is_flag': True}]},
 {'module': 'ttsforge.cli.commands_phonemes',
  'function': 'phonemes_preview',
  'name': 'preview',
  'parent': 'phonemes',
  'help': 'Preview phonemes for given text.\n'
          '\n'
          'Shows how text will be converted to phonemes and optionally tokens.\n'
          'Use --play to hear the audio output.\n'
          '\n'
          'Examples:\n'
          '\n'
          '    ttsforge phonemes preview "Hello world"\n'
          '\n'
          '    ttsforge phonemes preview "Hello world" --tokens\n'
          '\n'
          '    ttsforge phonemes preview "Hello world" --language de\n'
          '\n'
          '    ttsforge phonemes preview "König" --language de --play\n'
          '\n'
          '    ttsforge phonemes preview "Hermione" --play --phoneme-dict custom.json\n'
          '\n'
          '    ttsforge phonemes preview "Hello" --play --voice "af_nicole:50,am_michael:50"',
  'parameters': [{'name': 'text',
                  'kind': 'argument',
                  'decls': ['text'],
                  'annotation': 'str',
                  'help': None},
                 {'name': 'language',
                  'kind': 'option',
                  'decls': ['-l', '--language'],
                  'annotation': 'str',
                  'python_type': 'str',
                  'help': "Language code for phonemization (e.g., 'de', 'en-us', 'a' for auto).",
                  'default': 'a'},
                 {'name': 'tokens',
                  'kind': 'option',
                  'decls': ['--tokens'],
                  'annotation': 'bool',
                  'help': 'Show token IDs in addition to phonemes.',
                  'is_flag': True},
                 {'name': 'vocab_version',
                  'kind': 'option',
                  'decls': ['--vocab-version'],
                  'annotation': 'str',
                  'python_type': 'str',
                  'help': 'Vocabulary version to use.',
                  'default': 'v1.0'},
                 {'name': 'play',
                  'kind': 'option',
                  'decls': ['-p', '--play'],
                  'annotation': 'bool',
                  'help': 'Play audio preview of the text.',
                  'is_flag': True},
                 {'name': 'voice',
                  'kind': 'option',
                  'decls': ['-v', '--voice'],
                  'annotation': 'str',
                  'python_type': 'str',
                  'help': 'Voice to use for audio preview, or voice blend (e.g., '
                          "'af_nicole:50,am_michael:50').",
                  'default': 'af_sky'},
                 {'name': 'phoneme_dict',
                  'kind': 'option',
                  'decls': ['--phoneme-dict'],
                  'annotation': 'Path | None',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Path to custom phoneme dictionary file.',
                  'default': None}]},
 {'module': 'ttsforge.cli.commands_phonemes',
  'function': 'phonemes_info',
  'name': 'info',
  'parent': 'phonemes',
  'help': 'Show information about a phoneme file.\n'
          '\n'
          "PHONEME_FILE should be a JSON file created by 'ttsforge phonemes export'.\n"
          '\n'
          'Use --stats to show detailed token statistics (min, median, mean, max).',
  'parameters': [{'name': 'phoneme_file',
                  'kind': 'argument',
                  'decls': ['phoneme_file'],
                  'annotation': 'Path',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': None},
                 {'name': 'stats',
                  'kind': 'option',
                  'decls': ['--stats'],
                  'annotation': 'bool',
                  'help': 'Show detailed token statistics.',
                  'is_flag': True}]},
 {'module': 'ttsforge.cli.commands_utility',
  'function': 'voices',
  'name': 'voices',
  'parent': None,
  'help': 'List available TTS voices.',
  'parameters': [{'name': 'language',
                  'kind': 'option',
                  'decls': ['-l', '--language'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['a', 'b', 'd', 'e', 'f', 'h', 'i', 'j', 'p', 'z'],
                  'help': 'Filter voices by language (default: all languages).',
                  'default': None}]},
 {'module': 'ttsforge.cli.commands_utility',
  'function': 'demo',
  'name': 'demo',
  'parent': None,
  'help': 'Generate a demo audio file with all available voices.\n'
          '\n'
          'Creates a single audio file with samples from each voice, or separate files\n'
          'for each voice with --separate. Great for previewing and comparing voices.\n'
          '\n'
          'Supports voice blending with --blend or --blend-presets options.\n'
          '\n'
          'Examples:\n'
          '\n'
          '    ttsforge demo\n'
          '\n'
          '    ttsforge demo -l a  # Only American English voices\n'
          '\n'
          '    ttsforge demo -v af_heart,am_adam  # Specific voices\n'
          '\n'
          '    ttsforge demo --separate -o ./voices/  # Separate files in directory\n'
          '\n'
          '    ttsforge demo --text "Custom message from {voice}!"\n'
          '\n'
          '    ttsforge demo --blend "af_nicole:50,am_michael:50"  # Custom voice blend\n'
          '\n'
          '    ttsforge demo --blend-presets  # Demo all preset voice blends\n'
          '\n'
          '    ttsforge demo --play  # Play directly without saving\n'
          '\n'
          '    ttsforge demo -v af_heart --play  # Play a single voice demo',
  'parameters': [{'name': 'ctx', 'kind': 'context'},
                 {'name': 'output',
                  'kind': 'option',
                  'decls': ['-o', '--output'],
                  'annotation': 'Path | None',
                  'python_type': 'Path',
                  'path': {'exists': False,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Output file path (default: ./voices_demo.wav).',
                  'default': None},
                 {'name': 'language',
                  'kind': 'option',
                  'decls': ['-l', '--language'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['a', 'b', 'd', 'e', 'f', 'h', 'i', 'j', 'p', 'z'],
                  'help': 'Filter voices by language (default: all languages).',
                  'default': None},
                 {'name': 'voices_filter',
                  'kind': 'option',
                  'decls': ['-v', '--voice', 'voices_filter'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Specific voices to include (comma-separated, e.g., 'af_heart,am_adam').",
                  'default': None},
                 {'name': 'speed',
                  'kind': 'option',
                  'decls': ['-s', '--speed'],
                  'annotation': 'float',
                  'python_type': 'float',
                  'help': 'Speech speed (default: 1.0).',
                  'default': 1.0},
                 {'name': 'use_gpu',
                  'kind': 'option',
                  'decls': ['--gpu/--no-gpu', 'use_gpu'],
                  'annotation': 'bool | None',
                  'help': 'Enable/disable GPU acceleration.',
                  'default': None},
                 {'name': 'silence',
                  'kind': 'option',
                  'decls': ['--silence'],
                  'annotation': 'float',
                  'python_type': 'float',
                  'help': 'Silence between voice samples in seconds (default: 0.5).',
                  'default': 0.5},
                 {'name': 'text',
                  'kind': 'option',
                  'decls': ['--text'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': 'Custom text to use (use {voice} placeholder for voice name).',
                  'default': None},
                 {'name': 'separate',
                  'kind': 'option',
                  'decls': ['--separate'],
                  'annotation': 'bool',
                  'help': 'Save each voice as a separate file instead of concatenating.',
                  'is_flag': True},
                 {'name': 'blend',
                  'kind': 'option',
                  'decls': ['--blend'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Voice blend to demo (e.g., 'af_nicole:50,am_michael:50').",
                  'default': None},
                 {'name': 'blend_presets',
                  'kind': 'option',
                  'decls': ['--blend-presets'],
                  'annotation': 'bool',
                  'help': 'Demo a curated set of voice blend combinations.',
                  'is_flag': True},
                 {'name': 'play_audio',
                  'kind': 'option',
                  'decls': ['-p', '--play', 'play_audio'],
                  'annotation': 'bool',
                  'help': 'Play audio directly (also saves to file if -o specified).',
                  'is_flag': True}]},
 {'module': 'ttsforge.cli.commands_utility',
  'function': 'download',
  'name': 'download',
  'parent': None,
  'help': 'Download ONNX model and voice files required for TTS.\n'
          '\n'
          'Downloads from Hugging Face (onnx-community/Kokoro-82M-v1.0-ONNX).\n'
          '\n'
          'Quality options:\n'
          '  fp32     - Full precision (326 MB) - Best quality, default\n'
          '  fp16     - Half precision (163 MB) - Good quality, smaller\n'
          '  q8       - 8-bit quantized (92 MB) - Good quality, compact\n'
          '  q8f16    - 8-bit with fp16 (86 MB) - Smallest file\n'
          '  q4       - 4-bit quantized (305 MB)\n'
          '  q4f16    - 4-bit with fp16 (155 MB)\n'
          '  uint8    - Unsigned 8-bit (177 MB)\n'
          '  uint8f16 - Unsigned 8-bit with fp16 (114 MB)',
  'parameters': [{'name': 'ctx', 'kind': 'context'},
                 {'name': 'force',
                  'kind': 'option',
                  'decls': ['--force'],
                  'annotation': 'bool',
                  'help': 'Force re-download even if files exist.',
                  'is_flag': True},
                 {'name': 'quality',
                  'kind': 'option',
                  'decls': ['--quality', '-q'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['fp32', 'fp16', 'q8', 'q8f16', 'q4', 'q4f16', 'uint8', 'uint8f16'],
                  'help': 'Model quality/quantization level. Default: from config or fp32.',
                  'default': None}]},
 {'module': 'ttsforge.cli.commands_utility',
  'function': 'config',
  'name': 'config',
  'parent': None,
  'help': 'Manage ttsforge configuration.\n'
          '\n'
          'Configuration is stored in ~/.config/ttsforge/config.json',
  'parameters': [{'name': 'show',
                  'kind': 'option',
                  'decls': ['--show'],
                  'annotation': 'bool',
                  'help': 'Show current configuration.',
                  'is_flag': True},
                 {'name': 'reset',
                  'kind': 'option',
                  'decls': ['--reset'],
                  'annotation': 'bool',
                  'help': 'Reset configuration to defaults.',
                  'is_flag': True},
                 {'name': 'set_option',
                  'kind': 'option',
                  'decls': ['--set', 'set_option'],
                  'annotation': 'tuple[tuple[str, str], ...]',
                  'help': 'Set a configuration option.',
                  'multiple': True,
                  'nargs': 2,
                  'metavar': 'KEY VALUE'}]},
 {'module': 'ttsforge.cli.commands_utility',
  'function': 'short_sentence_advanced_config',
  'name': 'short-sentence-advanced-config',
  'parent': None,
  'help': 'Create, link, or show the advanced short-sentence JSON configuration.\n'
          '\n'
          "ACTION is 'init', 'show', or 'reset'. Called without ACTION, this help is\n"
          'shown.',
  'parameters': [{'name': 'ctx', 'kind': 'context'},
                 {'name': 'action',
                  'kind': 'argument',
                  'decls': ['action'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'choices': ['show', 'init', 'reset'],
                  'case_sensitive': False,
                  'help': None,
                  'required': False,
                  'metavar': 'ACTION'}]},
 {'module': 'ttsforge.cli.commands_utility',
  'function': 'extract_names',
  'name': 'extract-names',
  'parent': None,
  'help': 'Extract proper names from a book and generate phoneme dictionary.\n'
          '\n'
          'Scans INPUT_FILE (EPUB or TXT) for proper names and creates a JSON phoneme\n'
          'dictionary with auto-generated pronunciation suggestions. You can then review\n'
          'and edit the suggestions before using them for TTS conversion.\n'
          '\n'
          'Examples:\n'
          '\n'
          '    \x08\n'
          '    # Extract names and save to default file\n'
          '    ttsforge extract-names mybook.epub\n'
          '\n'
          '    \x08\n'
          '    # Preview names without saving\n'
          '    ttsforge extract-names mybook.epub --preview\n'
          '\n'
          '    \x08\n'
          '    # Extract frequent names only (10+ occurrences)\n'
          '    ttsforge extract-names mybook.epub --min-count 10 -o names.json\n'
          '\n'
          '    \x08\n'
          '    # Extract from specific chapters\n'
          '    ttsforge extract-names mybook.epub --chapters 1,3,5-10\n'
          '\n'
          '    \x08\n'
          '    # Extract from chapter range\n'
          '    ttsforge extract-names mybook.epub --start 5 --end 15\n'
          '\n'
          '    \x08\n'
          '    # Then use the dictionary for conversion\n'
          '    ttsforge convert mybook.epub --phoneme-dict custom_phonemes.json',
  'parameters': [{'name': 'input_file',
                  'kind': 'argument',
                  'decls': ['input_file'],
                  'annotation': 'Path',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': None},
                 {'name': 'output',
                  'kind': 'option',
                  'decls': ['-o', '--output'],
                  'annotation': 'Path | None',
                  'python_type': 'Path',
                  'path': {'exists': False,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': 'Output JSON file path (default: INPUT_FILE_custom_phonemes.json).',
                  'default': None},
                 {'name': 'min_count',
                  'kind': 'option',
                  'decls': ['--min-count'],
                  'annotation': 'int',
                  'python_type': 'int',
                  'help': 'Minimum occurrences for a name to be included (default: 3).',
                  'default': 3},
                 {'name': 'max_names',
                  'kind': 'option',
                  'decls': ['--max-names'],
                  'annotation': 'int',
                  'python_type': 'int',
                  'help': 'Maximum number of names to extract (default: 500).',
                  'default': 500},
                 {'name': 'language',
                  'kind': 'option',
                  'decls': ['-l', '--language'],
                  'annotation': 'str',
                  'python_type': 'str',
                  'choices': ['a', 'b', 'd', 'e', 'f', 'h', 'i', 'j', 'p', 'z'],
                  'help': 'Language for phoneme generation (default: a).',
                  'default': 'a'},
                 {'name': 'include_all',
                  'kind': 'option',
                  'decls': ['--include-all'],
                  'annotation': 'bool',
                  'help': 'Include all detected proper nouns (ignore min-count).',
                  'is_flag': True},
                 {'name': 'preview',
                  'kind': 'option',
                  'decls': ['--preview'],
                  'annotation': 'bool',
                  'help': 'Preview extracted names without saving to file.',
                  'is_flag': True},
                 {'name': 'chunk_size',
                  'kind': 'option',
                  'decls': ['--chunk-size'],
                  'annotation': 'int',
                  'python_type': 'int',
                  'help': 'Characters per chunk for processing (default: 100000).',
                  'default': 100000},
                 {'name': 'chapters',
                  'kind': 'option',
                  'decls': ['--chapters'],
                  'annotation': 'str | None',
                  'python_type': 'str',
                  'help': "Specific chapters to process (e.g., '1,3,5-10' or 'all'). Default: all.",
                  'default': None}]},
 {'module': 'ttsforge.cli.commands_utility',
  'function': 'list_names',
  'name': 'list-names',
  'parent': None,
  'help': 'List all names in a phoneme dictionary for review.\n'
          '\n'
          'Displays the contents of a phoneme dictionary in a readable table format,\n'
          'making it easy to review and identify names that need phoneme corrections.\n'
          '\n'
          'Use --play to interactively listen to each name pronunciation.\n'
          '\n'
          'Examples:\n'
          '\n'
          '    \x08\n'
          '    # List names sorted by frequency\n'
          '    ttsforge list-names custom_phonemes.json\n'
          '\n'
          '    \x08\n'
          '    # List names alphabetically\n'
          '    ttsforge list-names custom_phonemes.json --sort-by alpha\n'
          '\n'
          '    \x08\n'
          '    # Interactive audio preview\n'
          '    ttsforge list-names custom_phonemes.json --play\n'
          '\n'
          '    \x08\n'
          '    # Audio preview with different voice and language\n'
          '    ttsforge list-names custom_phonemes.json --play --voice af_bella --language de',
  'parameters': [{'name': 'phoneme_dict',
                  'kind': 'argument',
                  'decls': ['phoneme_dict'],
                  'annotation': 'Path',
                  'python_type': 'Path',
                  'path': {'exists': True,
                           'file_okay': True,
                           'dir_okay': True,
                           'readable': True,
                           'writable': False,
                           'resolve_path': False},
                  'help': None},
                 {'name': 'sort_by',
                  'kind': 'option',
                  'decls': ['--sort-by'],
                  'annotation': 'str',
                  'python_type': 'str',
                  'choices': ['name', 'count', 'alpha'],
                  'help': 'Sort by: name (same as alpha), count (occurrences), alpha '
                          '(alphabetical).',
                  'default': 'count'},
                 {'name': 'play',
                  'kind': 'option',
                  'decls': ['--play'],
                  'annotation': 'bool',
                  'help': 'Play audio preview for each name (interactive mode).',
                  'is_flag': True},
                 {'name': 'voice',
                  'kind': 'option',
                  'decls': ['-v', '--voice'],
                  'annotation': 'str',
                  'python_type': 'str',
                  'help': 'Voice to use for audio preview (default: af_sky).',
                  'default': 'af_sky'},
                 {'name': 'language',
                  'kind': 'option',
                  'decls': ['-l', '--language'],
                  'annotation': 'str',
                  'python_type': 'str',
                  'help': "Language code for audio preview (e.g., 'de', 'en-us', 'a' for auto, "
                          'default: a).',
                  'default': 'a'}]}]
